// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcnorknuocsztrxtiboc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjbm9ya251b2NzenRyeHRpYm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTU0MzYsImV4cCI6MjA1OTgzMTQzNn0.TN2S21_plu0ysVP-sgOig7tXtFv76T0D16yD6ONkOpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);